[package]
name = "chimes-store-dbs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
rust-version.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
url.workspace = true
clap.workspace = true
derivative.workspace = true
futures-lite.workspace = true
async-task.workspace = true
itertools.workspace = true
log.workspace = true
regex.workspace = true
lazy_static.workspace = true
base64.workspace = true
base16ct.workspace = true
rand.workspace = true
sha2.workspace = true
sha1.workspace = true
md5.workspace = true
simple_logger.workspace = true
toml.workspace = true
fastdate.workspace = true
substring.workspace = true
chrono.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
rbs.workspace = true
rbdc.workspace = true
rbatis.workspace = true
chimes-dbs-factory.workspace = true
chimes-store-core.workspace = true
salvo.workspace = true
