enable = true
validate_token_only = false
enable_captcha = false
validate_url = ""
validate_basic = true
user_search = "object://com.siline.chimes/ChimesUser#find_one"
role_search = "query://com.siline.chimes/FindRoles#search"
username_field = "username"
user_state_field = "enabled"
user_credentials_field = "password"
user_lock_field = "is_locked"
userid_field = "user_id"
role_name_field = "role_code"
credential_hash_method = "rsa"
credential_key = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKF+1MyYMe/jdl0Of0FgRzUhHv5ehJ1nAuzyNN6N6Gpd55QUSX0VukRpMPa3IP9odPF+I9pAChVJJfZeY339t18CAwEAAQ=="
credential_solt = "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAoX7UzJgx7+N2XQ5/QWBHNSEe/l6EnWcC7PI03o3oal3nlBRJfRW6RGkw9rcg/2h08X4j2kAKFUkl9l5jff23XwIDAQABAkB+h1OMtNWzQMDU6e3UN+2yd6/D1iQK+tF0+dNoZ0CoTIntMvvhrzaYRXPc5CXjUmZ7BthNDpkiHGsSOp3OKthxAiEAzCdplSfyrLhyKSl+Y+M5HCd6WYSd1o99S7lO9Rt1A9cCIQDKghNnRoS3U60kVocBTpQtpp1kiYpCUQ4SS1nOtuN3uQIgPn3t/t9clGxdXaY67x6V071t4UsL+aqwouZVegfumL8CIQCp9IUIVdyoZ2eWabAgXqxpq73IVM5eXdxraiXTIRbCsQIgbP7KXXuloNG5/O8FeKTN+ThcZrkPqka98KiBTx+Jmgo="
token_solt = "manabest"
token_expire = 180000
fail_bypass = true
app_name = "comstar"
enable_organization = false
organization_field = "ORG_ID"
data_permission = true
relative_table = "ac_base_user"
permit_userfield = "username"
permit_relative_field = "user_id"
enable_api_secure = true
check_relative_user = false

[[app_secret_keys]]
app_id = "siddkZIXldJt0NE"
app_secret = "7AFJTZJ342GibE8GAda4JZeDb_iDXrrvJDni"
username = "admin"
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcmlkIjoiMSIsInN1cGVyYWRtaW4iOnRydWUsImRvbWFpbiI6ImNvbXN0YXIiLCJleHAiOjE4MjQxNDI2MDF9.qMuRij1mmbDMwUGW_n7MWvXkuu_kwdF1BFgr4lk8GNg"
